### ISSUE TITLE
你好，请问是怎么部署到服务器的，菜鸟一枚求指点

### ISSUE THREAD

**Issue by ysq1051838264** [sosout/react-antd#11]
你好，请问是怎么部署到服务器的，菜鸟一枚求指点

**Comment by sosout** [comment]
@ysq1051838264 之前我在segmentfault写过一篇文章供您参考：[vue、react等单页面项目应该这样子部署到服务器](https://segmentfault.com/a/1190000012675012)，希望对您有所帮助！
