### ISSUE TITLE
没有样式

### ISSUE THREAD

**Issue by walter211** [sosout/react-antd#3]
按照readme搭建起来后没有样式咧?

**Comment by walter211** [comment]
还有登录界面的输入框为什么怪怪的？

**Comment by sosout** [comment]
您好，搭建过程中有没有出错？ 输入框怪在哪里？ 您运行起来和我本地上的一样吗

**Comment by sosout** [comment]
我刚刚又测试了一遍，是ok的

**Comment by sosout** [comment]
index.html文件里，热替换模式下去掉引用app.css，正常模式下必须引用<link href="/antd/dist/app.css" rel="stylesheet" />
