### ISSUE TITLE
yarn run dev 报错

### ISSUE THREAD

**Issue by Kennytian** [sosout/react-antd#5]
yarn run dev

node_modules/extract-text-webpack-plugin/index.js:187
                throw new Error("Breaking change: extract now only takes a single argument. Either an options " +
                ^

Error: Breaking change: extract now only takes a single argument. Either an options object *or* the loader(s).
Example: if your old code looked like this:
    ExtractTextPlugin.extract('style-loader', 'css-loader')

You would change it to:
    ExtractTextPlugin.extract({ fallback: 'style-loader', use: 'css-loader' })

**Comment by sosout** [comment]
webpack版本升级，忘记把npm run dev （正常编译模式，注意：index.html里必须手动引用app.css，{linkHtml}，否则没有样式）的代码迭代了，强烈推荐用 npm run hot （热替换编译模式，注意：热替换模式下index.html里去掉引用app.css）。分两个模式目的告知如何实现热替换
