### ISSUE TITLE
热更新

### ISSUE THREAD

**Issue by guchenhui** [sosout/react-antd#6]
大兄弟，这个项目热更新是不是有些问题啊

**Comment by sosout** [comment]
怎么说？具体说下

**Comment by guchenhui** [comment]
开发模式下，修改代码，保存后，没法实时在浏览器中看到变化。你自己试一下？

**Comment by sosout** [comment]
@guchenhui 我这边并没有如您所说热加载模式不可使用（由于引入包过多，热加载有点慢，同时在有卡死现象，由于最近一直在老家，接下来会对该问题进行优化），您确定下最新代码，同时提供下您所用的开发环境和开发工具。

**Comment by guchenhui** [comment]
是太慢了- -我很多次改完，保存，我可能等个五分钟浏览器才更新最新，期间怎么刷新都没用。这个问题很严重的呀，你忙的话，我有空帮你改改

**Comment by sosout** [comment]
@guchenhui 五分钟？ 您说的情况我这边都没有发现！如果您有好的方法，欢迎贡献代码，我们一起维护！

**Comment by sosout** [comment]
@guchenhui 老家山沟沟的网络，也最多7s左右，我会用webpack-bundle-analyzer,生成分析图看下是不是编译了哪些不需要便衣队第三方的库。

**Comment by guchenhui** [comment]
嗯，我想上班，下班我再看看
